
project_id = "swlqrejfgvmjajhtoall"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[realtime]
enabled = true
ip_version = "ipv6"

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
additional_redirect_urls = ["https://lvlbogdhtsupabaseurl.lovableproject.com/**"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
site_url = "http://localhost:3000"
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[functions.validate-ticket]
verify_jwt = true

[functions.create-payment-preference]
verify_jwt = true

[functions.create-payment]
verify_jwt = true

[functions.webhook-payment]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.send-ticket-email]
verify_jwt = false

[functions.dashboard-summary]
verify_jwt = true

[functions.get-profile]
verify_jwt = true

[functions."tickets/validate-ticket"]
verify_jwt = true

[functions."payments/create-payment-preference"]
verify_jwt = true

[functions."admin/dashboard-summary"]
verify_jwt = true

[functions."users/get-profile"]
verify_jwt = true

[functions."fidelity/get-user-balance"]
verify_jwt = true

[functions."fidelity/redeem-reward"]
verify_jwt = true

[functions."fidelity/list-rewards"]
verify_jwt = false

[functions."admin/manage-rewards"]
verify_jwt = true

[edge_runtime]
policy = "per_worker"
inspector_port = 8083
