// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uyyvncbfqvhoevpgtugp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV5eXZuY2JmcXZob2V2cGd0dWdwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk4MzcwMjgsImV4cCI6MjA1NTQxMzAyOH0.mDNUOQq-ZRIoobY4XfLwXwNF8XoszbB9Ymj4cxHkWPk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);